### ISSUE TITLE
There is a issue of "npm install"

### ISSUE THREAD

**Issue by YeatsLu** [jshttp/compressible#19]
This issue is related with [mime-db#182](https://github.com/jshttp/mime-db/issues/182)

**Comment by viditpandey** [comment]
Hi,
We are also facing this issue in our project. The build is failing with error log: **"No matching version found for mime-db@>= 1.43.0 < 2"**

**Comment by dougwilson** [comment]
Neither I, nor Travis CI, is having an issue installing from npm registry. Please check if you are using a mirror, otherwise contact npm support.
